name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy pylint
        pip install types-PyYAML types-tqdm types-requests
        
    - name: Format check with Black
      run: |
        black --check --line-length 100 .
      continue-on-error: true
      
    - name: Import sorting with isort
      run: |
        isort --check-only --profile black --line-length 100 .
      continue-on-error: true
      
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --max-complexity=10 --max-line-length=100 --statistics \
          --exclude=.git,__pycache__,docs/source/conf.py,old,build,dist
      continue-on-error: true
      
    - name: Type checking with mypy
      run: |
        mypy --ignore-missing-imports --follow-imports=skip \
          --strict-optional --warn-redundant-casts --warn-unused-ignores \
          --disallow-untyped-defs --no-implicit-reexport \
          --strict-equality --warn-unreachable \
          model.py utils.py dataset.py config.py train.py inference.py
      continue-on-error: true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        pytorch-version: ['2.0.0', '2.1.0']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-test-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-test-
          
    - name: Install PyTorch ${{ matrix.pytorch-version }}
      run: |
        python -m pip install --upgrade pip
        pip install torch==${{ matrix.pytorch-version }} torchvision --index-url https://download.pytorch.org/whl/cpu
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-xdist
        
    - name: Run unit tests
      run: |
        pytest tests/ -v --cov=. --cov-report=xml --cov-report=html
      continue-on-error: true
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.python-version }}-${{ matrix.pytorch-version }}
      continue-on-error: true

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        
    - name: Create test data
      run: |
        python tests/create_test_data.py
      continue-on-error: true
        
    - name: Test model creation
      run: |
        python -c "from model import create_model; model = create_model('transformer'); print('Model created successfully')"
        
    - name: Test data loading
      run: |
        python -c "from dataset import DXADataset, get_data_transforms; print('Dataset modules loaded successfully')"
        
    - name: Test configuration
      run: |
        python -c "from config import TrainingConfig, InferenceConfig, create_default_configs; create_default_configs('test_configs'); print('Config created successfully')"

  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install safety
      run: |
        pip install safety
        
    - name: Run safety check
      run: |
        safety check --json
      continue-on-error: true

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: dxa-to-3d:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
      continue-on-error: true

  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install documentation dependencies
      run: |
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
        pip install -r requirements.txt
        
    - name: Build documentation
      run: |
        cd docs && make html
      continue-on-error: true
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html/
      continue-on-error: true

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [lint, test, integration-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      